meta_product_name: "TEMPlate"
meta_title: "TEMPlate - The perfect jobsite for the gig economy"
meta_description: "The quickest and easiest way to find short term work that suits your lifestyle."
meta_image: "Template Cover Photo.png"
